@startuml
class 保護者 {
    保護者ID
    氏名
    連絡先
    LINEアカウントID
    子供情報: 子供[]
}

class 子供 {
    子供ID
    氏名
}

class 授業 {
    授業ID
    日時
    定員
}

class 欠席情報 {
    欠席ID
    子供ID
    授業ID
    欠席理由
    欠席日時
    振替情報
}

enum 通知種類 {
    欠席連絡,
    振替申請結果,
}

enum 振替理由 {
    保護者都合,
    事務局都合,
}

class メッセージングシステム {
    受信者LINEアカウントID取得(保護者ID)
    メッセージ送信(メッセージ内容, 通知種類, 受信者LINEアカウントID)
}

class LINE通知 {
    メッセージ送信(メッセージ内容, 受信者LINEアカウントID)
}

class 事務局 {
    担当者情報
    LINEアカウントID
    振替申請審査()
}

class システム {
    設定情報
    欠席情報登録(保護者, 欠席情報)
    振替可能日時検索(授業ID)
    定員確認(授業ID, 希望日時)
    振替申請処理(子供ID)
    通知送信(通知内容, 保護者)
    エラー処理()
}

システム -- メッセージングシステム
メッセージングシステム -- LINE通知
保護者 -- システム
事務局 -- システム
振替理由 -- 欠席情報
通知種類 -- システム

保護者 "1" o-- "*" 子供
子供 ..> 欠席情報
欠席情報 -- 授業
@enduml