@startuml
title 習い事振替システム

left to right direction
actor 保護者
actor 事務局

保護者 --> (ログインする) : Lineでログイン
保護者 --> (通知する) : Lineで通知
rectangle {
    保護者 --> (欠席連絡する)
    保護者 --> (振替可能日を確認する)
    保護者 --> (振替希望する)
}

事務局 --> (ログインする)
事務局 --> (通知する) : Lineで通知
rectangle {
    事務局 --> (中止連絡する)
    事務局 --> (振替可能日を設定する)
    事務局 --> (欠席確認する)
    事務局 --> (振替する)
}
@enduml