@startuml
actor 保護者
actor 事務局

usecase 欠席連絡
usecase 振替申請
usecase 授業情報確認

保護者 -- (欠席連絡)
保護者 -- (振替申請)
保護者 -- (授業情報確認)
事務局 -- (振替申請)

rectangle システム

(欠席連絡) -- システム
(振替申請) -- システム
(授業情報確認) -- システム

@enduml